services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: true

  LinkORB\Bundle\WikiBundle\Repository\WikiEventRepository:
    arguments: ['@doctrine']
    tags: ['doctrine.repository_service']

  LinkORB\Bundle\WikiBundle\Repository\WikiPageRepository:
    arguments: ['@doctrine']
    tags: ['doctrine.repository_service']

  LinkORB\Bundle\WikiBundle\Repository\WikiRepository:
    arguments: ['@doctrine']
    tags: ['doctrine.repository_service']

  LinkORB\Bundle\WikiBundle\Form\WikiPageType:
    arguments: ['@LinkORB\Bundle\WikiBundle\Repository\WikiPageRepository']
    public: false
    tags:
      - { name: form.type, alias: LinkORB\Bundle\WikiBundle\Form\WikiPageType }

  LinkORB\Bundle\WikiBundle\Form\WikiType:
    arguments: ['@LinkORB\Bundle\WikiBundle\Repository\WikiRepository']
    public: false
    tags:
      - { name: form.type, alias: LinkORB\Bundle\WikiBundle\Form\WikiType }

  LinkORB\Bundle\WikiBundle\Services\WikiEventService:
    arguments:
      - '@security.token_storage'
      - '@doctrine.orm.default_entity_manager'
      - '@LinkORB\Bundle\WikiBundle\Repository\WikiEventRepository'
